### PR TITLE
ADD : travis integration

### PR DESCRIPTION
**Pull request by Poltuu**
Continuous integration made easy !

https://travis-ci.org/LuccaSA/lucca-ui

### CODE REVIEW

**Comment by lucienbertin** [comment]
[noice](http://www.urbandictionary.com/define.php?term=noice&defid=1690307), can it launch transpilation tasks or is it just to validate PR by running the unit tests ?

**Comment by Poltuu** [comment]
this one is just for kama. the future is ours

**Comment by Poltuu** [comment]
It plays kamra on every push, each branch and so on

**Comment by lucienbertin** [comment]
https://www.youtube.com/watch?v=o6F6u5TIUbI

**Comment by lucienbertin** [comment]
might need to remove `npm install` cuz it takes 40s to do so about 50% of build time.

also there is only 3s of karma running for a build of 1 min 20 sec, it seems highly not optimized

**Comment by Poltuu** [comment]
well, improving CI is another problem. I'll let you play with it, but there is a lot of warning and self resolution of problem involved with this build, so you might want to take a couple of hours to see how stuff could be improved if you find it too slow. Anyway, it works.

**Comment by lucienbertin** [comment]
i like the check next to the PR
 - v it passes travis
 - v no conflicts from mybranch to master

**Pull request merged**
